[versions]
# libraries
junit = "6.0.1" # https://mvnrepository.com/artifact/org.junit.jupiter/junit-jupiter-api
assertj = "3.27.6"  # https://mvnrepository.com/artifact/org.assertj/assertj-core

# plugins
kotlin = "2.2.21" # https://kotlinlang.org/docs/releases.html
pluginPublish = "2.0.0" # https://plugins.gradle.org/plugin/com.gradle.plugin-publish

[libraries]
jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
jupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }
assertj = { group = "org.assertj", name = "assertj-core", version.ref = "assertj" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
pluginPublish = { id = "com.gradle.plugin-publish", version.ref = "pluginPublish" }
